name: Second Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Print greeting
        run: echo "Hello world"
      - name: 
        run: echo "Done - bye!"
      - name: Using a github action
        uses: actions/checkout@v3
      - name: Install node
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: nom ci
      - run: npm test
          
